# Generated by Django 4.2.7 on 2023-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_verified_email_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Телефон"
            ),
        ),
    ]
