# Generated by Django 4.2.7 on 2023-11-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.review",
            ),
        ),
    ]
